dist: bionic

# services:
#   - docker

jobs:
  include:
    - language: cpp

      env:
      # PASSWORD_OPENSSL
      - secure: "oFwwUc6mVA9/IcvLn8XT++P5NciwrSX3gHaW0gGObym3msYFf7L3yb9ROjh21KT6XbooJ+sh+3QetbziN2knvI3+3snnTg+2HZ/ALJxiNYuTZpsohArDPPVLAZkSBuPZUg2oceHdiInPuzpos+in4KBqRwCxHFjgQVZhXek+5Qu73F/46Jy7J8kTWNirZuxXC5eaWBkekcAXQQ8vEQtK8MwjOcA89b/Stx17KelTTeCxA1GRcSv4eBMjZD7X1j7s7JvoCfEwaAa0Q1CuAsbZ4hPUTNLHNUFr89LzQadvpJZrFGmwhuLKmkdo6TKtD4xYX8kl7fAh/xEKhFuiJjB+0dxLepyxmU81r/o3sg1UlUuvEXScD0ZI4w6Vd7C/apo9zmTIOB6cSa8qL3CeFkkflouT/pmKtR0fhqZBCUdEOMOKhUChDovveKOOoHyxOTmavKtvbjbuGx7dYhVPUNsDiH5qXQEf5kiQDDRKIC2uj/L812Sk9gNfZzHieX6sUPwDDmRUUkP/HFvrTBjN2TrjA9YwP0MQffKe+3Qcz6/iCL619JtDQre/cKmiflopRlU1+nbw+hI5VU790SQuHE32fuFANLtomOlqY5BsUPJBFjVZBtJA4txlH/mxk/WmtblxaTaxH2wRYM9JLElztjRGgt3PXanu/NA/7mDyLAGx+Ek="

      addons:
        apt:
          sources:
          - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ focal main universe'
          packages:
          - cppcheck
          # clang is needed to generate compile_commands.json with cmake.
          - clang-10
          # update gcc to the latest version
          - gcc-10
          - g++-10
          # clang-format/clang-tidy is not embedded in clangbuiltlinux/ubuntu:latest
          - clang-format
          - clang-tidy
          - clang-tools
          - iwyu
          - libboost-dev

      before_install:
        # latest published version.
        # - docker pull gcc:latest
        # master version. Does not include clang-format/clang-tidy.
        # - docker pull clangbuiltlinux/ubuntu:latest
        # - docker run --rm gcc:latest g++ --version
        # - docker run --rm clangbuiltlinux/ubuntu:latest clang++-11 --version
        - cppcheck --version
        - clang-format --version
        # You must add options either openssl will says :
        # *** WARNING : deprecated key derivation used.
        - openssl aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -k "$PASSWORD_OPENSSL" -out travis/ci/github_wiki_le_garrec_fr.key -in travis/ci/github_wiki_le_garrec_fr.key.enc -d
        # Open a connection to the authentication agent so ssh-add work.
        - eval $(ssh-agent -s)
        # ssh-add says:
        # Permissions 0664 for 'travis/ci/github_wiki_le_garrec_fr.key' are too open.
        # It is required that your private key files are NOT accessible by others.
        - chmod 600 travis/ci/github_wiki_le_garrec_fr.key
        - ssh-add travis/ci/github_wiki_le_garrec_fr.key

      script:
        # - docker run --rm -v "$PWD":/usr/src/templateweak -w /usr/src/templateweak gcc:latest g++ cpp/template/weak/ClasseA.cpp cpp/template/weak/ClasseB.cpp cpp/template/weak/main.cpp -Wall -Werror -Wextra -Wpedantic -fanalyzer -O2
        # - docker run --rm -v "$PWD":/usr/src/templateweak -w /usr/src/templateweak clangbuiltlinux/ubuntu:latest clang++-11 cpp/template/weak/ClasseA.cpp cpp/template/weak/ClasseB.cpp cpp/template/weak/main.cpp -Weverything -Werror -fsyntax-only -O2

        - sh travis/cpp.sh

    - language: python
      python: 3.8
      addons:
        apt:
          packages:
          - libboost-dev
      before_install:
        - python3 -m pip install --upgrade pip
      script:
        - mkdir buildcppgcc; cd buildcppgcc
        - cmake ../cpp
        - make cmake_fmt
        - cd ..
        - bash ./ini-lint-check.sh
        - shellcheck **/*.sh

    - language: ruby
      rvm: 2.7
      env:
      # GITHUB_PERSONAL_TOKEN
      - secure: "RLGSrpiyYZILp6urxYkaRLu2UvtF+eyqZ0PUDxFgUgFHXCW/AaXBOkd8y4ECzBEKHD5DdIv+y4bGkYInVyoH4onDYG/MKQJzgvrsuqz2BHqsSSUIwBtKtISgSAgSwhM/B8Na3NqjypliVsGc7lL+T51ORxG1g5h3cOjLq0/Ob/TrUxkdK5WC9pxblS89KlPxXO4YVgq5p6QPzvrzgEXl9OCHCIKa1qog+OuZ8EEx0HQJ9kPBfiz8wsHCAUpHR/0a2wb3TQj9ZQZv5mtzasQ95a8om6ha1FNhjL/1PuC3nnvk8iYpHSK2hJ54TmZ+er1o/QDLgN1yjU9v9UgZkIIqWCatvHaY+BMXCjVHZWpI9tnOLqz9vcuxNF3IXYl+e/d0riJXh1ZIcUB1qbg10mcN/X9U4W1w/Fe3s8uiAaLZ6bH0Wd+9qhXYbNqhT05VH+8UtB1pnXPrI0u9Uhn8DDW5yC7sVMAElBS508kcLMGFwOl8fi/X4RKbGi2GS9b/6YDCaX5d0nHX0gGOVQsOBQLVhXlD6o0Zm57p3z1HZK/s03MV/l7RI/h4ktiRJItspUhzGTCEm8eBl2JWASmb2PCrXrp1YkItlgHMqs1X02OWDfqvMBp9sUkFA5vOjw9sej6b0qrqsBHpn9uqEgQS4wtwP3ym1/HaiaOOmMmHc/dsjqw="
      before_install:
        - gem install bundler
      script:
        # log before travis lint to avoid :
        # invalid access token - try running travis login
        - bash ./travis-lint-check.sh

    - language: node_js
      node_js: node
      before_install:
        - npm install --no-save stylelint stylelint-config-standard
      script:
        - cd css
        - npx stylelint **/*.css
